### ISSUE TITLE
How does one contact support?

### ISSUE THREAD

**Issue by zachgarwood** [robocorp/robocorp-old#1]
I'm trying to contact customer support, but I cannot find any indication of how to do this on your website or from inside your app. Please add an easily findable method for developers to be able to contact you.

-----

In the meantime, here is my customer support request:

Customer: Havoc Shield (exmplorg7268c1529eef49d4aece7583875cb7bf)
Contact: zgarwood@havocshield.com
Issue: There are three long-running processes whose robots have already finished, but they still continue to run. On the process runs' details page, clicking the "Terminate run" does nothing.

![image](https://user-images.githubusercontent.com/2098951/125508000-2ca1810e-4cd1-4eff-b8ad-525ec16dcd83.png)

**Comment by zachgarwood** [comment]
Tagging @jayjayb772

**Comment by kariharju** [comment]
Sorry for the late reply @zachgarwood, 

The support actions are in the tools and Control Room so you can submit issues directly from the tools. This gives us the needed details without multiple back-n-forth questions.
