### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'screnshot.png'

### ISSUE THREAD

**Issue by ishandutta2007** [robocorp/robocorp-old#3]
``` 
   from RPA.Images import Images
   lib = Images()
   screenshot = lib.take_screenshot(filename="screnshot")

```

>   screenshot = lib.take_screenshot(filename="screnshot")
>   File "C:\Users\hp\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\RPA\Images.py", line 171, in take_screenshot
>     mss.tools.to_png(image.rgb, image.size, output=filename)
>   File "C:\Users\hp\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\mss\tools.py", line 60, in to_png
>     with open(output, "wb") as fileh:
> PermissionError: [Errno 13] Permission denied: 'screnshot.png'

it runs fine when triggered explicitly from terminal but when
 run from job it fails

**Comment by kariharju** [comment]
Issue probably meant for: https://github.com/robocorp/rpaframework
